### ISSUE TITLE
Background shortly flashes

### ISSUE THREAD

**Issue by jonny65** [WFoundation/WF.Player.Android#10]
Background shortly flashes between 2 messageboxes. On multimessages or dialogs the backgound very shortly flashes between 2 messages. Check it with the "Wherigo Testsuite" > Item "Tools" > Background flashes

**Comment by charlenni** [comment]
Inserted a 100 ms delay before removing old screen. So it don't flicker, when in this time a new screen is displayed.

Availible at version 0.3.5.
