### ISSUE TITLE
Picturesize not adjusting

### ISSUE THREAD

**Issue by jonny65** [WFoundation/WF.Player.Android#8]
Bug or feature ? ;-) Pictures keep their original dimensions. Bad, because there are a lot of different screen resolutions on player devices. I would suggest to make it configurable that pictures keep their size or will fit to screen. 
Check it with the "Wherigo Testsuite" > Item "Picturesize"

**Comment by charlenni** [comment]
Default behavior could be set via "Settings" from version 0.3.5.
