### ISSUE TITLE
WF.Player sometimes crashes (hard)

### ISSUE THREAD

**Issue by jonny65** [WFoundation/WF.Player.Android#9]
At start of a cartridge or while running the wf.player gets a blank screen, only with title (see pic attached). The player don't respond. After killing the task it is not possible to start again.The blank screen will be shown again. Only after rebooting the device the wf.player can be started again. It happens on different cartridges at different points. So its not possible that a certain cartridge is the reason.

Unfortunately not to check and nothing informative things in the logfile. How about a continously written debugfile ? It happens not so rarely, I would say on 10 playerstarts it crashes in 2 or 3 cases.

![blankscreen](https://f.cloud.github.com/assets/6563334/2059212/3a36a080-8b9e-11e3-912a-8ac11c114294.jpg)

**Comment by charlenni** [comment]
It seems to be an OutOfMemory error. Had to look into this.

**Comment by charlenni** [comment]
Changed the handling of bitmaps, so they don't use so much memory and mark them for GC after usage.

Availible at version 0.3.5.

**Comment by jonny65** [comment]
Since 0.3.5 very rarely, but I have had 1 crash with the same effect (empty screen, no reaction) on 0.3.5 but it can not be (as the crashes before), reproduced. I think a detailled debug info (detailed logfile) is needed. The standard log is not significant enough.
